save_dir: '../output/testing_aml/'

model_params:
    node_type: 'square'

data_params:
    path_to_x_list:  '../data/aml_data_tr.pkl' #'../data/aml_data_tr.pkl' #
    path_to_labels: '../data/aml_labels_tr.pkl' #'../data/aml_labels_tr.pkl'   #
    path_to_idxs:
    test_percent: .05

transform_params:
    cells_to_subsample: 10000
    num_cells_for_transformer: 100000
    transform_type: 'umap' 

gate_init_multi_heuristic_params:
    num_gates: 5
    run_kde_first: False
train_params:
    #n_epoch: 20
    conv_thresh: 0.00001
    learning_rate_classifier: 0.001
    learning_rate_gates: .05
    l1_reg_strength: .00
    feat_diff_reg: .00
    descent_type: 'coordinate_descent'
    num_gates_to_learn: 1
    


