save_dir: '../output/multidim_rect/'

plot_umap_reflection: False

model_params:
    node_type: 'hyperrectangle'
    logistic_k: 100
    feature_diff_penalty: .010

data_params:
    path_to_x_list: '../data/cll/data_for_UMAP_with_filtering/x_UMAP_dev.pkl' #'../data/aml_data_tr.pkl' #
    path_to_labels: '../data/cll/data_for_UMAP_with_filtering/y_UMAP_dev.pkl' #'../data/aml_labels_tr.pkl'   #
    path_to_idxs: '../data/cll/data_for_UMAP_with_filtering/sample_ids_UMAP_dev.pkl'
    test_percent: .05

transform_params:
    cells_to_subsample: 10000
    num_cells_for_transformer: 100000
    transform_type: 'umap' 
    # use_labels_to_transform_data: True

gate_init_cluster_params:
    n_clusters: 5
    run_kde_first: False

train_params:
    conv_thresh: 0.000001
    learning_rate_classifier: 0.001
    learning_rate_gates: .005
    l1_reg_strength: .01
    descent_type: 'coordinate_descent'
    num_gates_to_learn: 1
      
