

save_dir: '../output/umap_tr_on_dev_te_on_val/'

model_params:
    node_type: 'square'
    feature_diff_penalty: .0010

data_params:
#    path_to_x_list: '../data/cll/data_for_UMAP_with_filtering/x_UMAP_dev.pkl' #'../data/cll/data_for_UMAP_with_filtering/x_UMAP_val.pkl' #data_for_UMAP_with_filtering/x_UMAP_dev.pkl #'../data/aml_data_tr.pkl' #
#    path_to_labels: '../data/cll/data_for_UMAP_with_filtering/y_UMAP_dev.pkl' #'./data/cll/data_for_UMAP_with_filtering/y_UMAP_val.pkl' #data_for_UMAP_with_filtering/y_UMAP_dev.pkl' #'../data/aml_labels_tr.pkl'   #
#    path_to_idxs: '../data/cll/data_for_UMAP_with_filtering/sample_ids_UMAP_dev.pkl'

    use_presplit_data: True
    presplit_data:
        x_tr: '../data/cll/data_for_UMAP_with_filtering/x_UMAP_dev.pkl'
        x_te: '../data/cll/data_for_UMAP_with_filtering/x_UMAP_val.pkl'
        y_tr: '../data/cll/data_for_UMAP_with_filtering/y_UMAP_dev.pkl'
        y_te: '../data/cll/data_for_UMAP_with_filtering/y_UMAP_val.pkl'
        idxs_tr: '../data/cll/data_for_UMAP_with_filtering/sample_ids_UMAP_dev.pkl'
        idxs_te: '../data/cll/data_for_UMAP_with_filtering/sample_ids_UMAP_val.pkl'

transform_params:
    cells_to_subsample: 10000
    num_cells_for_transformer: 100000
    transform_type: 'umap' 

gate_init_cluster_params:
    n_clusters: 5
    run_kde_first: False

train_params:
    #n_epoch: 20
    conv_thresh: 0.00001
    learning_rate_classifier: 0.001
    learning_rate_gates: .05
    l1_reg_strength: .00
    descent_type: 'coordinate_descent'
    num_gates_to_learn: 1
