save_dir: '../output/default_umap/'

model_params:
    node_type: 'square'

data_params:
    path_to_x_list:  '../data/cll/x_UMAP_dev.pkl' #'../data/aml_data_tr.pkl' #
    path_to_labels: '../data/cll/y_UMAP_dev.pkl' #'../data/aml_labels_tr.pkl'   #
    test_percent: .05

transform_params:
    cells_to_subsample: 10
    num_cells_for_transformer: 100
    transform_type: 'umap' 

gate_init_multi_heuristic_params:
    num_gates: 5
    num_gridcells_per_axis: 10
    init_type: 'heuristic_grid'

train_params:
    #n_epoch: 20
    conv_thresh: 0.00001
    learning_rate_classifier: 0.001
    learning_rate_gates: .05
    l1_reg_strength: .00
    feat_diff_reg: .00
    descent_type: 'coordinate_descent'
    


